 rinha2 Pulling 
 rinha1 Pulling 
 rinha1 Pulled 
 rinha2 Pulled 
 Network jpcairesf-java_default  Creating
 Network jpcairesf-java_default  Created
 Container postgres  Creating
 Container postgres  Created
 Container rinha2  Creating
 Container rinha1  Creating
 Container rinha2  Created
 Container rinha1  Created
 Container jpcairesf-java-nginx-1  Creating
 Container jpcairesf-java-nginx-1  Created
Attaching to nginx-1, postgres, rinha1, rinha2
postgres  | The files belonging to this database system will be owned by user "postgres".
postgres  | This user must also own the server process.
postgres  | 
postgres  | The database cluster will be initialized with locale "en_US.utf8".
postgres  | The default database encoding has accordingly been set to "UTF8".
postgres  | The default text search configuration will be set to "english".
postgres  | 
postgres  | Data page checksums are disabled.
postgres  | 
postgres  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres  | creating subdirectories ... ok
postgres  | selecting dynamic shared memory implementation ... posix
postgres  | selecting default max_connections ... 100
postgres  | selecting default shared_buffers ... 128MB
postgres  | selecting default time zone ... UTC
postgres  | creating configuration files ... ok
postgres  | running bootstrap script ... ok
postgres  | sh: locale: not found
postgres  | 2024-02-16 10:29:06.253 UTC [31] WARNING:  no usable system locales were found
nginx-1   | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1   | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1   | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1   | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1   | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1   | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1   | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1   | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1   | /docker-entrypoint.sh: Configuration complete; ready for start up
postgres  | performing post-bootstrap initialization ... ok
nginx-1   | 2024/02/16 10:29:08 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.21.0.4:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/16 10:29:08 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.21.0.3:8080/clientes/1/extrato", host: "localhost:9999"
postgres  | syncing data to disk ... ok
postgres  | 
postgres  | 
postgres  | Success. You can now start the database server using:
postgres  | 
postgres  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres  | 
postgres  | initdb: warning: enabling "trust" authentication for local connections
postgres  | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
postgres  | waiting for server to start....2024-02-16 10:29:08.479 UTC [37] LOG:  starting PostgreSQL 16.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit
postgres  | 2024-02-16 10:29:08.481 UTC [37] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres  | 2024-02-16 10:29:08.491 UTC [40] LOG:  database system was shut down at 2024-02-16 10:29:06 UTC
postgres  | 2024-02-16 10:29:08.497 UTC [37] LOG:  database system is ready to accept connections
postgres  |  done
postgres  | server started
postgres  | CREATE DATABASE
postgres  | 
postgres  | 
postgres  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/script.sql
postgres  | CREATE TABLE
postgres  | CREATE TABLE
postgres  | CREATE INDEX
postgres  | CREATE SEQUENCE
postgres  | ALTER TABLE
postgres  | INSERT 0 5
postgres  | 
postgres  | 
postgres  | waiting for server to shut down....2024-02-16 10:29:08.666 UTC [37] LOG:  received fast shutdown request
postgres  | 2024-02-16 10:29:08.669 UTC [37] LOG:  aborting any active transactions
postgres  | 2024-02-16 10:29:08.672 UTC [37] LOG:  background worker "logical replication launcher" (PID 43) exited with exit code 1
postgres  | 2024-02-16 10:29:08.672 UTC [38] LOG:  shutting down
postgres  | 2024-02-16 10:29:08.675 UTC [38] LOG:  checkpoint starting: shutdown immediate
postgres  | 2024-02-16 10:29:09.161 UTC [38] LOG:  checkpoint complete: wrote 936 buffers (5.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.291 s, sync=0.181 s, total=0.490 s; sync files=307, longest=0.152 s, average=0.001 s; distance=4296 kB, estimate=4296 kB; lsn=0/1922778, redo lsn=0/1922778
postgres  | 2024-02-16 10:29:09.166 UTC [37] LOG:  database system is shut down
postgres  |  done
postgres  | server stopped
postgres  | 
postgres  | PostgreSQL init process complete; ready for start up.
postgres  | 
postgres  | 2024-02-16 10:29:09.189 UTC [1] LOG:  starting PostgreSQL 16.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit
postgres  | 2024-02-16 10:29:09.190 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres  | 2024-02-16 10:29:09.190 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres  | 2024-02-16 10:29:09.195 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres  | 2024-02-16 10:29:09.202 UTC [55] LOG:  database system was shut down at 2024-02-16 10:29:09 UTC
postgres  | 2024-02-16 10:29:09.209 UTC [1] LOG:  database system is ready to accept connections
rinha1    | 
rinha1    |   .   ____          _            __ _ _
rinha1    |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
rinha1    | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
rinha1    |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
rinha1    |   '  |____| .__|_| |_|_| |_\__, | / / / /
rinha1    |  =========|_|==============|___/=/_/_/_/
rinha1    |  :: Spring Boot ::                (v3.2.2)
rinha1    | 
rinha2    | 
rinha2    |   .   ____          _            __ _ _
rinha2    |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
rinha2    | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
rinha2    |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
rinha2    |   '  |____| .__|_| |_|_| |_\__, | / / / /
rinha2    |  =========|_|==============|___/=/_/_/_/
rinha2    |  :: Spring Boot ::                (v3.2.2)
rinha2    | 
rinha1    | 2024-02-16T10:29:10.025Z  INFO 1 --- [           main] c.r.r.RinhaJavaApplication               : Starting RinhaJavaApplication v0.0.1-SNAPSHOT using Java 17.0.2 with PID 1 (/BOOT-INF/classes started by root in /)
rinha1    | 2024-02-16T10:29:10.027Z  INFO 1 --- [           main] c.r.r.RinhaJavaApplication               : No active profile set, falling back to 1 default profile: "default"
nginx-1   | 2024/02/16 10:29:10 [error] 30#30: *4 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
rinha2    | 2024-02-16T10:29:10.420Z  INFO 1 --- [           main] c.r.r.RinhaJavaApplication               : Starting RinhaJavaApplication v0.0.1-SNAPSHOT using Java 17.0.2 with PID 1 (/BOOT-INF/classes started by root in /)
rinha2    | 2024-02-16T10:29:10.423Z  INFO 1 --- [           main] c.r.r.RinhaJavaApplication               : No active profile set, falling back to 1 default profile: "default"
nginx-1   | 2024/02/16 10:29:12 [error] 30#30: *5 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/16 10:29:14 [error] 30#30: *6 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
rinha1    | 2024-02-16T10:29:14.922Z  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
rinha2    | 2024-02-16T10:29:15.316Z  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
rinha1    | 2024-02-16T10:29:15.422Z  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 491 ms. Found 2 JPA repository interfaces.
rinha2    | 2024-02-16T10:29:15.717Z  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 393 ms. Found 2 JPA repository interfaces.
nginx-1   | 2024/02/16 10:29:16 [error] 30#30: *7 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/16 10:29:18 [error] 30#30: *8 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
rinha2    | 2024-02-16T10:29:19.326Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8080 (http)
rinha1    | 2024-02-16T10:29:19.334Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8080 (http)
rinha2    | 2024-02-16T10:29:19.420Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
rinha2    | 2024-02-16T10:29:19.420Z  INFO 1 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.18]
rinha1    | 2024-02-16T10:29:19.428Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
rinha1    | 2024-02-16T10:29:19.428Z  INFO 1 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.18]
rinha1    | 2024-02-16T10:29:20.248Z  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
nginx-1   | 2024/02/16 10:29:20 [error] 30#30: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.21.0.3:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/16 10:29:20 [error] 30#30: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.21.0.4:8080/clientes/1/extrato", host: "localhost:9999"
rinha1    | 2024-02-16T10:29:20.315Z  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 9826 ms
rinha2    | 2024-02-16T10:29:20.323Z  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
rinha2    | 2024-02-16T10:29:20.325Z  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 9586 ms
nginx-1   | 2024/02/16 10:29:22 [error] 30#30: *12 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
rinha2    | 2024-02-16T10:29:22.322Z  INFO 1 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
rinha1    | 2024-02-16T10:29:22.326Z  INFO 1 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
rinha1    | 2024-02-16T10:29:22.625Z  INFO 1 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 6.4.1.Final
rinha2    | 2024-02-16T10:29:22.632Z  INFO 1 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 6.4.1.Final
rinha1    | 2024-02-16T10:29:22.825Z  INFO 1 --- [           main] o.h.c.internal.RegionFactoryInitiator    : HHH000026: Second-level cache disabled
rinha2    | 2024-02-16T10:29:22.827Z  INFO 1 --- [           main] o.h.c.internal.RegionFactoryInitiator    : HHH000026: Second-level cache disabled
rinha2    | 2024-02-16T10:29:23.829Z  INFO 1 --- [           main] o.s.o.j.p.SpringPersistenceUnitInfo      : No LoadTimeWeaver setup: ignoring JPA class transformer
rinha2    | 2024-02-16T10:29:24.017Z  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
rinha1    | 2024-02-16T10:29:24.020Z  INFO 1 --- [           main] o.s.o.j.p.SpringPersistenceUnitInfo      : No LoadTimeWeaver setup: ignoring JPA class transformer
rinha1    | 2024-02-16T10:29:24.129Z  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
nginx-1   | 2024/02/16 10:29:24 [error] 30#30: *13 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
rinha2 exited with code 137
rinha1 exited with code 137
nginx-1   | 2024/02/16 10:29:26 [error] 30#30: *14 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/16 10:29:28 [error] 30#30: *15 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/16 10:29:30 [error] 30#30: *16 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/16 10:30:06 [error] 30#30: *17 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.21.0.3:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/16 10:30:25 [error] 30#30: *17 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.21.0.4:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/16 10:30:30 [error] 30#30: *20 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.21.0.3:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/16 10:30:30 [error] 30#30: *20 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/16 10:30:32 [error] 30#30: *22 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/16 10:30:34 [error] 30#30: *23 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/16 10:30:39 [error] 30#30: *24 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.21.0.4:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/16 10:30:39 [error] 30#30: *24 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/16 10:30:44 [error] 30#30: *26 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.21.0.3:8080/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/16 10:30:44 [error] 30#30: *26 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/16 10:30:46 [error] 30#30: *28 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1   | 2024/02/16 10:30:48 [error] 30#30: *29 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1 exited with code 0
nginx-1 exited with code 0
postgres  | 2024-02-16 10:30:51.223 UTC [1] LOG:  received fast shutdown request
postgres  | 2024-02-16 10:30:51.227 UTC [1] LOG:  aborting any active transactions
postgres  | 2024-02-16 10:30:51.230 UTC [1] LOG:  background worker "logical replication launcher" (PID 58) exited with exit code 1
postgres  | 2024-02-16 10:30:51.230 UTC [53] LOG:  shutting down
postgres  | 2024-02-16 10:30:51.234 UTC [53] LOG:  checkpoint starting: shutdown immediate
postgres  | 2024-02-16 10:30:51.288 UTC [53] LOG:  checkpoint complete: wrote 46 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.007 s, sync=0.032 s, total=0.059 s; sync files=13, longest=0.029 s, average=0.003 s; distance=261 kB, estimate=261 kB; lsn=0/1963CB8, redo lsn=0/1963CB8
postgres  | 2024-02-16 10:30:51.292 UTC [1] LOG:  database system is shut down
postgres exited with code 0
